import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: ' About Mohammed alkhateeb',
  description: 'Generated by create next app',
};

const About = () => {
  return (
    <>
      <h1>About mohammed alkhateeb</h1>
    </>
  );
};
export default About;
