import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: ' About Mohammed alkhateeb',
  description: 'Generated by create next app',
};
async function fetchRepos() {
  const response = await fetch(
    'https://api.github.com/users/bradtraversy/repos'
  );
  await new Promise<void>((resolve, reject) => {
    setTimeout(resolve, 1000);
  });
  const repos = await response.json();
  return repos;
}
{
}
const AboutTeam = async () => {
  const repos = await fetchRepos();
  return (
    <>
      <h1>About Team mohammed alkhateeb</h1>
      {repos.map((item: any) => {
        return (
          <>
            <div
              key={item.id}
              className='max-w-md w-full bg-white shadow-lg rounded-lg overflow-hidden mx-auto m-2'
            >
              <Link href={`/about/team/${item.name}`}>
                <div className='px-4 py-2'>
                  <h2 className='text-xl font-semibold text-gray-800'>
                    {item.name}
                  </h2>
                  <p className='text-gray-600 mt-2'>{item.description}</p>
                </div>
              </Link>
            </div>
          </>
        );
      })}
    </>
  );
};
export default AboutTeam;
