import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './Layout/Navbar';
import Sidebar from './Layout/Sidebar';
import AuthProvider from './context/AuthProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Mohammed alkhateeb',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <div className='flex'>
            {/* <Sidebar /> */}
            <div className='flex-1'>
              <Navbar />
              <main className='p-4'>{children}</main>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
